# O primeiro valor é o nome do livro, o segundo é o nome do autor e o terceiro é o preço do livro #

history_books = [['Uma Breve História do Tempo', 'Stephen Hawking', 55.00],
                 ['Sapiens: Uma Breve História da Humanidade', 'Yuval Noah Harari', 50.00],
                 ['Guerra e Paz', 'Liev Tolstói', 60.00],
                 ['1984', 'George Orwell', 65.00],
                 ['O Nome da Rosa', 'Umberto Eco', 46.99],
                 ['O Povo Brasileiro: A Formação e o Sentido do Brasil', 'Darcy Ribeiro', 40.00],
                 ['A Queda do Império Romano', 'Peter Heather', 35.00],
                 ['Guns, Germs, and Steel: The Fates of Human Societies', 'Jared Diamond', 45.00],
                 ['História do Brasil', 'Boris Fausto', 38.00],
                 ['O Capital', 'Karl Marx', 55.00],
                 ['A Guerra dos Tronos', 'George R. R. Martin', 60.00],
                 ['The Rise and Fall of the Third Reich: A History of Nazi Germany', 'William L. Shirer', 50.00],
                 ['As veias abertas da América Latina', 'Eduardo Galeano', 42.00],
                 ['Sobre a História da Filosofia Ocidental', 'Bertrand Russell', 48.00],
                 ['A Segunda Guerra Mundial', 'Antony Beevor', 55.00]]

fantasy_books = [['O Senhor dos Anéis', 'J.R.R. Tolkien', 40.00],
                 ['Sonho de uma noite de verão', 'William Shakespeare', 50.00],
                 ['Romeu e Julieta', 'William Shakespeare', 55.00],
                 ['Hamlet', 'William Shakespeare', 65.00],
                 ['Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 25.00],
                 ['As Crônicas de Nárnia', 'C.S. Lewis', 30.00],
                 ['Game of Thrones', 'George R.R. Martin', 45.00],
                 ['Harry Potter e a Câmara Secreta', 'J.K. Rowling', 27.00],
                 ['Harry Potter e o Prisioneiro de Azkaban', 'J.K. Rowling', 28.00],
                 ['Harry Potter e o Cálice de Fogo', 'J.K. Rowling', 30.00],
                 ['Harry Potter e a Ordem da Fênix', 'J.K. Rowling', 32.00],
                 ['Harry Potter e o Enigma do Príncipe', 'J.K. Rowling', 33.00],
                 ['Harry Potter e as Relíquias da Morte', 'J.K. Rowling', 35.00],
                 ['Mistborn: O Império Final', 'Brandon Sanderson', 38.00],
                 ['O Hobbit', 'J.R.R. Tolkien', 20.00],
                 ['A Guerra dos Tronos', 'George R.R. Martin', 40.00],
                 ['A Torre Negra: O Pistoleiro', 'Stephen King', 36.00],
                 ['O Nome do Vento', 'Patrick Rothfuss', 34.00],
                 ['O Último Desejo', 'Andrzej Sapkowski', 32.00],
                 ['O Feiticeiro de Terramar', 'Ursula K. Le Guin', 26.00],
                 ['Os Magos', 'Lev Grossman', 29.00],
                 ['Circe', 'Madeline Miller', 31.00],
                 ['Filha do Império', 'Raymond E. Feist e Janny Wurts', 37.00]]

# Para mangás, eu adicionei um quarto valor, que refere-se ao número de volumes da obra. #

mangas = [
    ['One Piece', 'Eiichiro Oda', 13.50, 1067],
    ['Dragon Ball', 'Akira Toriyama', 14.00, 519],
    ['Dragon Ball Super', 'Akira Toriyama', 11.00, 87],
    ["Tensei shitara slime data", "FUSE", 12.00, 95],
    ["Demon Slayer", "Koyoharu Gotouge", 13.00, 232],
    ["Blue lock", "Muneyuki Kaneshiro", 11.00, 204],
    ["Mushoko tensei", "Rifujin na Magonote", 15.00, 77],
    ["Fire force", "Atsushi Ōkubo", 13.50, 321],
    ["Sword art online", "Reki Kawahara", 9.75, 263],
    ["Overlord", "Kugane Maruyama", 11.25, 48],
    ["Tsukimichi", "Kei Azumi", 12.50, 87],
    ["Kaguya-sama: Love Is War", "Aka Akasaka", 15.00, 282],
    ["Mashle", "Hajime Komoto", 13.00, 124],
    ["Dr. Stone", "Riichiro Inagaki", 14.75, 232],
    ['Boku no Hero Academia', 'Kōhei Horikoshi', 9.50, 370],
    ['Jujutsu Kaisen', 'Gege Akutami', 15.50, 190],
    ['Vagabond', 'Takehiko Inoue', 14.00, 327],
    ['YU-GI-OH', 'Kazuki Takahashi', 9.00, '1000+'],
    ['Cavaleiros do Zodíaco: The Lost Canvas', 'Masami Kurumada', 12.00, 252],
    ['Yu Yu Hakusho', 'Yoshihiro Togashi', 10.00, 175],
    ['Hunter x Hunter', 'Yoshihiro Togashi', 11.50, '390 (em hiato)'],
    ['Magmell', 'Di Nian Miao', 9.00, 72],
    ['Sense Life', 'Glitch Tellend (Caio Ulisses)', 10.00, 130],
    ['Black Clover', 'Yūki Tabata', 10.00, 331],
    ['BERSERK', 'Kentaro Miura', 13.00, '364 (em hiato)'],
    ['Detetive Conan', 'Gosho Aoyama', 8.50, '1100+'],
    ['Doraemon', 'Fujiko F. Fujio', 7.00, '1400+'],
    ['Fruits Basket', 'Natsuki Takaya', 9.00, 136],
    ['Horimiya', 'HERO', 8.00, 122],
    ['Golden Boy', 'Tatsuya Egawa', 11.00, 70],
    ['Shingeki no Kyojin', 'Hajime Isayama', 12.00, 139],
    ['MONSTER', 'Naoki Urasawa', 11.50, 162],
    ['Tokyo Ghoul', 'Sui Ishida', 10.00, 179],
    ['Parasyte', 'Hitoshi Iwaaki', 9.00, 80],
    ['Battle Royale', 'Koushun Takami', 12.00, 152],
    ['Konosuba', 'Natsume Akatsuki', 11.00, 74],
    ['Re:zero', 'Tappei Nagatsuki', 10.50, 85],
    ['Kimetsu no Yaiba', 'Koyoharu Gotouge', 13.50, 205],
    ['Noragami', 'Adachitoka', 12.00, 122],
    ['Bakuman', 'Tsugumi Ohba', 11.00, 176],
    ['Fullmetal Alchemist', 'Hiromu Arakawa', 13.00, 108],
    ['Vinland Saga', 'Makoto Yukimura', 14.00, 179],
    ['Dororo', 'Osamu Tezuka', 12.00, 16],
    ['Dorohedoro', 'Q Hayashida', 13.00, 236],
    ['Naruto', 'Masashi Kishimoto', 12.00, 700],
    ['Tokyo Revengers', 'Ken Wakui', 12.99, 278],
    ['Classroom of the Elite', 'Shōgo Kinugasa', 11.50, 120],
    ['The Rising of the Shield Hero', 'Aneko Yusagi', 13.50, 83],
    ['Fairy Tail', 'Hiro Mashima', 14.00, 545],
    ['Chainsaw Man', 'Tatsuki Fujimoto', 12.75, 116],
    ['Log Horizon', 'Mamare Touno', 11.20, 47],
    ['Mob Psycho 100', 'ONE', 11.99, 101],
    ['Bungo Stray Dogs', 'Kafka Asagiri', 12.30, 99],
    ['Hells Paradise: Jigokuraku', 'Yūji Kaku', 13.80, 139],
    ['More than a Married Couple, but Not Lovers', 'Fumino Yuki', 10.99, 59],
    ['Masamune-kun\'s Revenge', 'Hazuki Takeoka', 11.90, 88],
    ['Arifureta: From Commonplace to World\'s Strongest', 'Ryō Shirakome', 12.20, 130],
    ['Food Wars! Shokugeki no Soma', 'Yūto Tsukuda', 14.20, 315],
    ['My Dress-Up Darling', 'Shinichi Fukuda', 13.70, 88],
    ['86: Eighty-Six', 'Asato Asato', 11.80, 86],
    ['Kenja no Mago', 'Tsuyoshi Yoshioka', 10.50, 82],
    ['The Irregular at Magic High School: The Archdemon\'s War (Akashic Records)', 'Tarō Hitsuji', 11.30, 23],
    ['Plunderer', 'Sukeno Riku', 12.40, 239],
    ['The Promised Neverland', 'Kaiu Shirai', 13.90, 214],
    ['Death Note', 'Tsugumi Ohba', 14.50, 108],
    ['Ore Dake Haireru Hidden Dungeon (Isekai Cheat Magician)', 'Meguru Seto', 12.80, 67],
    ['One-Punch Man', 'ONE', 13.20, 172],
    ['Another', 'Yukito Ayatsuji', 11.70, 24],
    ['Akame ga Kill!', 'Takahiro', 12.60, 78],
    ['Hellsing', 'Kouta Hirano', 13.70, 109],
    ["Shikimori's Not Just a Cutie", 'Keigo Maki', 10.90, 163]
]

# Para as comics, fiz o mesmo que nos mangás. O primeiro valor é o nome, o segundo o nome do autor, o terceiro o
# preço e o quarto a quantidade de volumes que a obra em questão possui até

comics = [["Watchmen", "Alan Moore e Dave Gibbons", 20, 12],
          ["Sandman: Prelúdio", "Neil Gaiman", 15, 5],
          ["V for Vendetta", "Alan Moore e David Lloyd", 18, 10],
          ["The Killing Joke", "Alan Moore e Brian Bolland", 12, 1],
          ["Batman: Ano Um", "Frank Miller e David Mazzucchelli", 25, 4],
          ["Kingdom Come", "Mark Waid e Alex Ross", 30, 4],
          ["Maus", "Art Spiegelman", 20, 1],
          ["Batman: O Cavaleiro das Trevas", "Frank Miller", 22, 4],
          ["Batman: A Piada Mortal", "Alan Moore e Brian Bolland", 15, 1],
          ["Marvels", "Kurt Busiek e Alex Ross", 28, 4],
          ["The League of Extraordinary Gentlemen", "Alan Moore e Kevin O'Neill", 20, 6],
          ["Sin City: A Dama de Vermelho", "Frank Miller", 15, 1],
          ["Persepolis", "Marjane Satrapi", 18, 2],
          ["Scott Pilgrim", "Bryan Lee O'Malley", 15, 6],
          ["Bone", "Jeff Smith", 20, 9],
          ["Hellboy: Sementes da Destruição", "Mike Mignola", 18, 4],
          ["Y: O Último Homem", "Brian K. Vaughan e Pia Guerra", 25, 5],
          ["Tartarugas Ninjas: O Último Ronin", "Kevin Eastman, Peter Laird, Tom Waltz", 22, 5],
          ["Scott Pilgrim contra o Mundo", "Bryan Lee O'Malley", 20, 6],
          ["Avatar: The Last Airbender - The Lost Adventures", "Gene Luen Yang, Michael Dante DiMartino", 25, 3]
          ]

romance_books = [["Orgulho e Preconceito", "Jane Austen", 40.0],
                 ["Cem Anos de Solidão", "Gabriel García Márquez", 48.0],
                 ["Amor nos Tempos do Cólera", "Gabriel García Márquez", 44.0],
                 ["E o Vento Levou", "Margaret Mitchell", 60.0],
                 ["O Morro dos Ventos Uivantes", "Emily Brontë", 36.0],
                 ["Anna Karenina", "Lev Tolstói", 52.0],
                 ["Jane Eyre", "Charlotte Brontë", 40.0],
                 ["Um Amor para Recordar", "Nicholas Sparks", 32.0],
                 ["O Diário de uma Paixão", "Nicholas Sparks", 36.0],
                 ["P.S. Eu Te Amo", "Cecelia Ahern", 40.0],
                 ["A Casa dos Espíritos", "Isabel Allende", 44.0],
                 ["O Amor nos Tempos do Cólera", "Gabriel García Márquez", 48.0],
                 ["Para Sempre Alice", "Lisa Genova", 40.0],
                 ["A Culpa é das Estrelas", "John Green", 36.0],
                 ["A Cabana", "William P. Young", 100.0],
                 ["O Pequeno Príncipe", "Antoine de Saint-Exupéry", 80.0],
                 ["A Menina que Roubava Livros", "Markus Zusak", 44.0],
                 ["A Hospedeira", "Stephenie Meyer", 44.0],
                 ["A Sombra do Vento", "Carlos Ruiz Zafón", 44.0],
                 ["Me Chame Pelo Seu Nome", "André Aciman", 48.0],
                 ["O Sol é para Todos", "Harper Lee", 52.0]
                 ]

horror_books = [["O Exorcista", "William Peter Blatty", 40.0],
                ["It: A Coisa", "Stephen King", 48.0],
                ["O Iluminado", "Stephen King", 44.0],
                ["O Cemitério", "Stephen King", 52.0],
                ["Carrie, A Estranha", "Stephen King", 36.0],
                ["Psicose", "Robert Bloch", 40.0],
                ["Drácula", "Bram Stoker", 32.0],
                ["Frankenstein", "Mary Shelley", 36.0],
                ["O Médico e o Monstro", "Robert Louis Stevenson", 40.0],
                ["Hell House", "Richard Matheson", 44.0],
                ["A Hora do Vampiro", "Stephen King", 48.0],
                ["O Retrato de Dorian Gray", "Oscar Wilde", 32.0],
                ["American Psycho", "Bret Easton Ellis", 56.0],
                ["O Silêncio dos Inocentes", "Thomas Harris", 48.0],
                ["O Corvo", "Edgar Allan Poe", 24.0],
                ["A Metamorfose", "Franz Kafka", 28.0],
                ["O Chamado de Cthulhu", "H.P. Lovecraft", 32.0],
                ["O Amuleto", "Stephen King", 40.0],
                ["O Estranho Caso de Charles Dexter Ward", "H.P. Lovecraft", 36.0],
                ["Histórias Extraordinárias", "Edgar Allan Poe", 40.0],
                ["A Assombração da Casa da Colina", "Shirley Jackson", 36.0],
                ["Misery: Louca Obsessão", "Stephen King", 52.0],
                ["O Mal Nosso de Cada Dia", "Donald Ray Pollock", 44.0],
                ["O Demonologista", "Andrew Pyper", 40.0],
                ["A Dança da Morte", "Stephen King", 56.0],
                ["O Bebê de Rosemary", "Ira Levin", 36.0],
                ["O Assassinato de Roger Ackroyd", "Agatha Christie", 32.0],
                ["Coraline", "Neil Gaiman", 32.0],
                ["O Homem de Giz", "C.J. Tudor", 40.0],
                ["O Vampiro Lestat", "Anne Rice", 48.0]
                ]

best_books = [['Jujutsu Kaisen', 'Gege Akutami', 10.50, 166],
              ['One Piece', 'Eiichiro Oda', 12.50, 1016],
              ['Dragon Ball', 'Akira Toriyama', 10.00, 519],
              ['Dragon Ball Super', 'Akira Toriyama', 11.00, 68],
              ['Boku no Hero Academia', 'Kōhei Horikoshi', 9.50, 341],
              ["Watchmen", "Alan Moore e Dave Gibbons", 20, 12],
              ["Scott Pilgrim contra o Mundo", "Bryan Lee O'Malley", 20, 6],
              ["Batman: O Cavaleiro das Trevas", "Frank Miller", 22, 4],
              ["Avatar: The Last Airbender - The Lost Adventures", "Gene Luen Yang, Michael Dante DiMartino", 25, 3],
              ['Hamlet', 'William Shakespeare', 65.00],
              ['Romeu e Julieta', 'William Shakespeare', 55.00],
              ["Drácula", "Bram Stoker", 32.0],
              ["Coraline", "Neil Gaiman", 32.0],
              ["O Chamado de Cthulhu", "H.P. Lovecraft", 32.0],
              ["O Corvo", "Edgar Allan Poe", 24.0],]    
